import Link from "next/link";
import type { ReactNode } from "react";
import { formatPhone, telUrl } from "./site";

export const legalDetails = {
  status: "draft" as "draft" | "published",
  updated: "October 2, 2026",
  legalName: null as string | null,
  mailingAddress: null as string | null,
  email: null as string | null,
  intakeProvider: null as string | null,
};

export type LegalDocument = {
  title: string;
  description: string;
  sections: { id: string; title: string; content: ReactNode }[];
};

function LegalContact() {
  return (
    <>
      <p>
        Direct privacy requests and legal notices to Pontian
        {legalDetails.email ? <> at <a href={`mailto:${legalDetails.email}`}>{legalDetails.email}</a></> : <> through the phone or WhatsApp channels on our <Link href="/contact">contact page</Link></>}.
        You can also call <a href={telUrl()}>{formatPhone()}</a>. Identify the request as a privacy request or legal notice and describe what you need. Do not send passwords, identity documents, or sensitive records with your initial request.
      </p>
      {legalDetails.mailingAddress && <p>Mailing address: {legalDetails.mailingAddress}.</p>}
    </>
  );
}

export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  description: "How Pontian handles website inquiries, business communications, and information entrusted to us during client work.",
  sections: [
    {
      id: "scope",
      title: "Who we are and what this policy covers",
      content: <>
        <p>Pontian{legalDetails.legalName ? `, operated by ${legalDetails.legalName},` : ""} builds custom software, connects business systems, and develops AI tools for business operations. In this policy, “Pontian,” “we,” and “us” refer to the operator of the Pontian website and business.</p>
        <p>This policy covers pontian.co, Pontian-operated versions of this website, our presentations and inquiry forms, and our direct communications with prospective clients, clients, suppliers, and partners. It explains our own handling of personal information, meaning information that identifies or can reasonably be linked to a person.</p>
        <p>When we process information for a client under its instructions, the client determines the purpose of that processing. The client’s privacy notice and our written processing agreement govern that work. A separate product notice applies where provided. This website policy does not replace a client platform’s privacy notice, a data processing agreement, or a healthcare business associate agreement.</p>
      </>,
    },
    {
      id: "collection",
      title: "Information we collect and where it comes from",
      content: <>
        <p>We receive information directly from you when you complete a form, call or message us, send correspondence, or participate in a business discussion. We may also receive relevant business contact details from your organization, a referral, or a publicly available professional source.</p>
        <ul>
          <li><strong>Contact details:</strong> your name, company, work email, and any telephone number or contact details you give us in correspondence.</li>
          <li><strong>Company context:</strong> your industry, company size, role, coordination methods, number of software platforms, knowledge storage, administrative workload, AI use, technology adoption, and reason for contacting Pontian. Write-in answers may contain information you choose to add.</li>
          <li><strong>Communications and business records:</strong> messages, meeting notes, proposals, service requirements, contracts, billing contacts, and records needed to manage an engagement. Recordings or transcripts require the notice or permission required by law.</li>
          <li><strong>Technical and security information:</strong> IP address, browser and device details, requested pages, timestamps, referring pages where available, verification results, and information generated by hosting and security services.</li>
          <li><strong>Client service information:</strong> documents, system records, project decisions, and other information a client authorizes us to handle. The agreed scope determines the categories involved. We do not gain access to a client’s systems simply because someone visits this website.</li>
        </ul>
        <p>The public inquiry forms require your name, company, and email. The general Get Started form also requires company-context answers. Without the required information and a successful security check, the online submission cannot be completed. You can contact us directly instead.</p>
        <p>The public website does not collect payment-card details, account passwords, or uploaded client files. Do not put health information, government identifiers, financial account details, credentials, children’s information, or confidential third-party records into the inquiry form.</p>
      </>,
    },
    {
      id: "forms",
      title: "What happens when you submit a form",
      content: <>
        <p>Your answers remain in the open page’s memory while you complete the form. The application does not save unfinished answers to a browser database or send each answer as you select it. Refreshing or leaving the page can clear them.</p>
        <p>When you send the form, our server receives the submitted contact details, answers, and verification token. It validates the submission and sends the token to Cloudflare for verification. After verification, accepted contact details and answers are forwarded to our configured inquiry-handling service with a submission timestamp and a label identifying the form. The Skorman contact form collects contact details without the ten-question questionnaire.</p>
        <p>{legalDetails.intakeProvider ? `Our inquiry-handling provider is ${legalDetails.intakeProvider}.` : "The inquiry-handling service may be a CRM or an automation provider acting for Pontian."} A failed verification prevents forwarding to that destination. A submission error does not establish that no technical information was processed or that a destination received no data. Contact us if you need to confirm receipt or request deletion.</p>
      </>,
    },
    {
      id: "uses",
      title: "Why we use information",
      content: <>
        <p>We use contact details and company context to respond to requests, assess whether an engagement fits, prepare proposals, and follow up on the conversation you started. We use business records to provide agreed services, coordinate work, maintain systems, manage billing, and keep a record of decisions.</p>
        <p>Technical information helps us deliver pages, troubleshoot failures, prevent spam and abuse, and protect the website. We may use relevant records to meet legal obligations, resolve disputes, and establish or defend legal claims.</p>
        <p>Submitting an inquiry requests a response about that inquiry. It does not enroll you in a general marketing list or authorize unrelated promotional calls or texts. If we offer optional marketing, we provide the choice required by law and a way to stop receiving it.</p>
      </>,
    },
    {
      id: "legal-bases",
      title: "Legal bases where required",
      content: <>
        <p>Where applicable law requires a legal basis, we rely on steps requested before entering a contract and performance of a contract for proposals and agreed services. Our legitimate interests support responding to business contacts, maintaining business records, and securing the website, provided those interests do not override your rights.</p>
        <p>We rely on legal obligations for required records and disclosures. We request consent when required for optional marketing, recording, or another activity that needs it. You may withdraw that consent without affecting processing that was lawful before withdrawal. Browsing the website or reading this policy is not consent to every possible use of your information.</p>
      </>,
    },
    {
      id: "storage",
      title: "Cookies, browser storage, and security checks",
      content: <>
        <p>The bilingual presentation and contact pages use a browser preference named <code>pontian-locale</code> to remember English or Portuguese. This is local storage on your device. It stays until you clear it or change the preference. It does not contain your form answers.</p>
        <p>Cloudflare Turnstile runs on the form’s final contact step to distinguish visitors from bots. It processes technical signals such as IP address, browser headers, TLS characteristics, and the website’s origin. Cloudflare processes signals on our behalf to provide verification and also processes them for its own security-improvement purposes. See the <a href="https://www.cloudflare.com/turnstile-privacy-policy/" target="_blank" rel="noreferrer">Turnstile Privacy Addendum</a> and <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noreferrer">Cloudflare Privacy Policy</a> for its handling of that information.</p>
        <p>Our website application does not include advertising pixels or tools for tracking you across unrelated sites. Hosting and security services may use necessary technical mechanisms. You can manage cookies and local storage through your browser, although blocking security scripts may prevent online submission.</p>
        <p>We do not sell personal information or share it for cross-context behavioral advertising. There is no such advertising activity on this website for a Do Not Track or Global Privacy Control signal to disable. Where law requires a response to a recognized privacy signal, we honor it.</p>
      </>,
    },
    {
      id: "sharing",
      title: "Who receives information",
      content: <>
        <p>We disclose information only for the purposes described in this policy or another purpose disclosed and permitted by law.</p>
        <ul>
          <li><strong>Hosting and security:</strong> Vercel hosts the website and processes requests and operational information. Cloudflare provides Turnstile verification. Vercel’s <a href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noreferrer">Privacy Notice</a> describes its own practices.</li>
          <li><strong>Business service providers:</strong> the configured inquiry-handling service, communications providers, and suppliers supporting agreed work receive the information needed for their functions. They are subject to the applicable service and data protection arrangements.</li>
          <li><strong>Authorized team members and contractors:</strong> people working on a request or engagement receive information needed for that work, subject to access limits and confidentiality obligations.</li>
          <li><strong>Your organization:</strong> we may share engagement information with the contacts your organization authorizes. Permission to contact one person does not grant every employee access to all project information.</li>
          <li><strong>Professional advisers and authorities:</strong> information may be disclosed for accounting, legal advice, a valid legal requirement, security, or the protection of legal rights. We assess requests and limit disclosure as required by law.</li>
          <li><strong>Business transfers:</strong> relevant information may be reviewed or transferred in a merger, acquisition, financing, or sale of assets, subject to appropriate confidentiality and data protection requirements. We provide notice of a change in control when required.</li>
        </ul>
        <p>We do not provide a visitor list to a company merely because we prepared a presentation for it. Contacting us through the Skorman page sends an inquiry to Pontian, not an automatic application to Skorman or a property’s leasing team.</p>
      </>,
    },
    {
      id: "client-data",
      title: "Client systems, AI, and confidential information",
      content: <>
        <p>Client engagements may involve databases, documents, transcripts, operational systems, and AI providers. Access, approved providers, permitted uses, security requirements, retention, and return or deletion of data must be defined in the client agreement and any required data processing agreement before that processing begins.</p>
        <p>The public website’s inquiry flow does not send your answers to an AI model. Prepared examples in presentations do not connect your browser to a client’s private systems. In an agreed AI service, authorized input may be sent to an approved model provider. Model outputs can contain personal information and require the same access and handling controls as the underlying input.</p>
        <p>We do not treat possession of client data as permission to reuse it for unrelated clients or to train general-purpose models. Any such use needs a separate lawful basis and the client’s written authorization. Provider retention and training settings must be assessed for the particular service rather than assumed from a marketing description.</p>
        <p>If your information is in a platform operated by one of our clients, contact that organization first. We assist with requests under our agreement with the client. We do not independently override its lawful instructions or disclose another person’s or client’s records.</p>
      </>,
    },
    {
      id: "international",
      title: "International processing",
      content: <>
        <p>Pontian works across countries, and hosting, security, communications, and project providers may process information in the United States or other locations where they operate. Those locations may have different privacy laws from your country.</p>
        <p>Where a restricted international transfer is involved, we use the lawful mechanism required for that transfer, such as an applicable adequacy decision or approved contractual safeguards. Client agreements must identify any required geographic restrictions. Visiting the website does not waive your statutory rights. Contact us for information about the safeguards applicable to your information.</p>
      </>,
    },
    {
      id: "retention",
      title: "How long information is kept",
      content: <>
        <p>We retain personal information for the time needed for its purpose, taking account of the nature of the information, the status of the relationship, legal requirements, and unresolved claims.</p>
        <ul>
          <li>Inquiry records are kept while we address the request and any relevant follow-up. We delete or anonymize them when they no longer serve that purpose, unless another lawful reason requires retention.</li>
          <li>Engagement, billing, and contract records are kept for the relationship and the applicable legal, tax, accounting, or limitation periods.</li>
          <li>Client data follows the retention and return or deletion instructions in the client agreement and applicable law.</li>
          <li>Technical logs follow the hosting or security service’s configured retention and any justified incident-preservation period.</li>
          <li>The language preference remains on your device until you remove it or change it.</li>
        </ul>
        <p>Deletion may take additional time to propagate through backups or provider systems. Information kept solely for recovery or a legal hold must remain restricted and must not be used for unrelated purposes. We explain an applicable retention exception when responding to a deletion request.</p>
      </>,
    },
    {
      id: "security",
      title: "Security",
      content: <>
        <p>We use measures appropriate to the information and processing involved, including access restrictions, HTTPS connections, server-side form validation, and verification before forwarding online inquiries. Client security controls are defined for each engagement.</p>
        <p>No transmission or storage system is guaranteed to be secure. A statement about a proposed control, uptime target, or acceptance test is not a certification or a guarantee that every client system has that control. If an incident requires notification, we provide it in accordance with applicable law and contractual obligations.</p>
      </>,
    },
    {
      id: "rights",
      title: "Your choices and privacy requests",
      content: <>
        <p>You can ask about our processing, request access or a copy, correct information, request deletion, restrict or object to a use, or withdraw consent. Which requests we must fulfill depends on the applicable law, our role, and any lawful exception. You can also ask us to stop optional marketing.</p>
        <p>Use the contact channels in the final section. Describe the relationship or form involved and the right you wish to exercise. We may request proportionate information to verify your identity or an agent’s authority. We use that verification information for handling the request and protecting the people concerned.</p>
        <p>We respond within the period required by applicable law and explain any lawful refusal, extension, or fee. We do not discriminate against you for exercising a protected right. Where available, you may appeal a refusal through the same contact channel and complain to the relevant regulator.</p>
      </>,
    },
    {
      id: "regional-rights",
      title: "Additional rights under regional laws",
      content: <>
        <p><strong>European Economic Area and United Kingdom.</strong> Where the GDPR or UK GDPR applies, your rights may include access, correction, erasure, restriction, portability, and withdrawal of consent. You may object to processing based on legitimate interests and to direct marketing. You can complain to your local supervisory authority or the UK Information Commissioner. The public inquiry flow does not make solely automated decisions with legal or similarly significant effects.</p>
        <p><strong>Brazil.</strong> Where the LGPD applies, you may request confirmation of processing, access, correction, anonymization, blocking or deletion of unnecessary or unlawful data, and portability subject to regulation. You may request information about recipients and consent choices, revoke consent, and request deletion of consent-based data subject to legal exceptions. You may challenge unlawful processing and request review of qualifying automated decisions. Complaints may be directed to the ANPD.</p>
        <p><strong>California and other U.S. states.</strong> If an applicable state privacy law covers our processing, you may have rights to know, access, correct, delete, receive a portable copy, or opt out of specified sale, sharing, targeted advertising, or profiling. California residents may also have rights concerning certain uses of sensitive information and authorized agents. Our collection and disclosure categories are described in this policy. We do not sell personal information or share it for behavioral advertising, and the public forms do not request sensitive personal information.</p>
        <p>These descriptions apply only where the relevant law grants the right and covers the processing. They do not remove any protection granted by another applicable law.</p>
      </>,
    },
    {
      id: "children",
      title: "Children and sensitive information",
      content: <>
        <p>This public business website and its inquiry forms are intended for adults acting in a business capacity. They are not directed to children under 13, and we do not knowingly collect their personal information through these forms. A parent or guardian who believes a child has provided information should contact us so we can address it and delete it where required.</p>
        <p>Education, healthcare, employee, or other regulated client services require their own appropriate notices, permissions, contracts, and controls. This policy does not establish compliance with COPPA, FERPA, HIPAA, or another sector-specific rule for an individual client platform.</p>
      </>,
    },
    {
      id: "third-parties",
      title: "Third-party websites and communications",
      content: <>
        <p>Property links, research sources, telephone links, and WhatsApp links may take you to another provider. If you contact us through WhatsApp, your carrier, device, and WhatsApp provider process communications under their own arrangements. Another website’s operator is responsible for its own notice and practices.</p>
        <p>We remain responsible for our own handling of information received through those channels. Linking to a provider does not make every part of its service subject to this policy.</p>
      </>,
    },
    {
      id: "changes",
      title: "Changes to this policy",
      content: <>
        <p>We update this policy when our practices or legal requirements change and identify the revision date. For a material change, we give additional notice where required. If a new purpose requires consent, we obtain it before starting that processing. A policy update does not retroactively authorize a use that required permission.</p>
      </>,
    },
    {
      id: "contact",
      title: "Contact Pontian",
      content: <LegalContact />,
    },
  ],
};

export const termsOfService: LegalDocument = {
  title: "Terms of Service",
  description: "Terms for the Pontian website, presentations, inquiries, and client engagements that expressly incorporate these terms.",
  sections: [
    {
      id: "scope",
      title: "Scope and acceptance",
      content: <>
        <p>These Terms of Service govern use of the Pontian public website, presentations, inquiry forms, and related materials. “Pontian,” “we,” and “us” mean {legalDetails.legalName || "the business operating under the Pontian name"}. “You” means the visitor or, where applicable, the organization you are authorized to represent.</p>
        <p>By accepting these Terms where presented, or using the website after having a reasonable opportunity to review them, you agree to them to the extent permitted by applicable law. If you do not agree, stop using the website. Mandatory rights remain in effect.</p>
        <p>Paid services require a separate written agreement. The provisions below addressing client services apply to an engagement only if that agreement expressly incorporates these Terms. Browsing, sending an inquiry, viewing a proposal, or speaking to us does not by itself purchase services or create a service contract.</p>
      </>,
    },
    {
      id: "authority",
      title: "Eligibility and authority",
      content: <>
        <p>The website’s business inquiry features are intended for people at least 18 years old, or the age of legal majority in their jurisdiction, who can enter a binding agreement. If you act for an organization, you must be authorized to provide its information and accept any terms on its behalf.</p>
        <p>Do not impersonate another person, misrepresent your authority, or submit another person’s private information without an appropriate basis. Any client product designed for younger users requires its own terms and permissions.</p>
      </>,
    },
    {
      id: "website",
      title: "Website access and permitted use",
      content: <>
        <p>We permit you to access the public website and use its materials to evaluate Pontian, understand our work, and communicate with us. You may share links and retain a copy of a publicly provided presentation for that evaluation, preserving credits and notices. Confidential or restricted materials remain subject to their stated restrictions.</p>
        <p>Access does not transfer ownership of the website, brand, source code, or presentation materials. You may not sell or republish our materials as your own, use our marks to imply an endorsement, or use the website to build a deceptive copy of our business. Rights of quotation, fair use, accessibility, and other uses permitted by law remain available.</p>
      </>,
    },
    {
      id: "acceptable-use",
      title: "Acceptable use",
      content: <>
        <p>You must use the website and any service lawfully and within the access granted to you. You may not:</p>
        <ul>
          <li>Submit spam, fraudulent inquiries, malicious code, threats, or content that unlawfully infringes another person’s rights.</li>
          <li>Bypass verification, access controls, rate limits, or security measures, or attempt to obtain another client’s or user’s information.</li>
          <li>Disrupt the site, overload infrastructure, or conduct intrusive testing without written authorization.</li>
          <li>Use automated collection in a way that disregards access restrictions, infringes rights, or materially harms the service. Ordinary indexing of public pages remains subject to applicable site instructions.</li>
          <li>Use software or AI outputs to make unlawful decisions, commit fraud, or represent unreviewed output as a professional approval or verified fact.</li>
        </ul>
        <p>Report suspected vulnerabilities through our contact channel. Reporting a vulnerability does not authorize access to private records, disruption, or disclosure of another person’s information.</p>
      </>,
    },
    {
      id: "inquiries",
      title: "Inquiries and communications",
      content: <>
        <p>Provide accurate contact details and only the company context needed to explain your request. You retain rights to the information you submit and give us permission to process it to respond and evaluate a possible engagement, as described in our <Link href="/privacy">Privacy Policy</Link>.</p>
        <p>A form confirmation means the submission was accepted by our configured delivery flow. It is not acceptance of an engagement, a promise of a response by a specific time, or confirmation that a proposal has been approved. If delivery is uncertain, use the direct contact options.</p>
        <p>Do not submit credentials, regulated records, private client files, or information subject to an NDA through the public form. An inquiry does not itself create an NDA. Agree on confidentiality and a suitable transfer method before sending those materials.</p>
        <p>An inquiry permits a relevant response. It does not provide blanket consent to unrelated marketing calls, automated texts, or recurring campaigns. Project messaging and notification systems require the applicable notices and permissions.</p>
      </>,
    },
    {
      id: "presentations",
      title: "Presentations, demos, and results",
      content: <>
        <p>Presentations may contain proposed features, fictional records, synthetic data, prepared AI answers, simulated connections, and renderings. A working interface or example does not establish a live integration, production availability, client approval, ownership of a property, or completion of a development.</p>
        <p>Property facts and research are attributed to their sources and may change. Availability, title, value, zoning, occupancy, and feasibility require independent verification. A mention of a client, property, vendor, or platform does not imply an endorsement or partnership beyond what we expressly state.</p>
        <p>Case studies describe the stated circumstances and do not guarantee a similar result. Forecasts, roadmaps, acceptance targets, timelines, search rankings, inquiry volumes, cost estimates, or savings become contractual commitments only when expressly included in an agreed written scope.</p>
      </>,
    },
    {
      id: "engagements",
      title: "Client agreements and order of precedence",
      content: <>
        <p>Each paid engagement must identify the parties, scope, deliverables, fees, dependencies, ownership or licenses, acceptance criteria, support, and termination arrangements in a written proposal, statement of work, or service agreement accepted by both parties. We call those documents the “Client Agreement.”</p>
        <p>A signed amendment controls the subjects it changes. A required data processing agreement or business associate agreement controls its specific data protection subject matter. The Client Agreement controls other conflicts with these Terms. A later marketing page or unilateral website revision does not amend an existing Client Agreement.</p>
        <p>When the Client Agreement incorporates these Terms, the following service provisions supply defaults only where the Client Agreement is silent. A client-owned application may also have separate terms for its end users. These Terms do not automatically bind those users.</p>
      </>,
    },
    {
      id: "delivery",
      title: "Scope, delivery, acceptance, and changes",
      content: <>
        <p>For an incorporated client engagement, Pontian performs the agreed work with reasonable professional care. Features, integrations, migration, training, documentation, and continuing improvements are included only to the extent stated in the scope.</p>
        <p>The client supplies lawful access, accurate inputs, a decision-maker, and timely reviews. A delay in those dependencies or an external provider may require a corresponding schedule adjustment, which we communicate. We do not use a delay to silently expand fees or scope.</p>
        <p>Acceptance follows the tests and process in the Client Agreement. A request outside the agreed scope requires a written change describing its effect on price, timing, and acceptance. A demo, roadmap item, or informal suggestion is not an approved change order.</p>
        <p>Support hours, response times, uptime commitments, backups, recovery objectives, on-site work, and emergency coverage apply only where agreed. The public website does not establish a service-level agreement.</p>
        <p>For an incorporated engagement, neither party is responsible for a delay caused by an event outside its reasonable control, provided it promptly informs the other party and takes reasonable steps to reduce the effect. This does not excuse payment for services already received or eliminate data protection and confidentiality duties. The Client Agreement governs any resulting adjustment or termination.</p>
      </>,
    },
    {
      id: "fees",
      title: "Fees, third-party costs, and renewal",
      content: <>
        <p>The Client Agreement determines implementation charges, milestone payments, recurring fees, taxes, payment deadlines, and approved third-party costs. We do not charge for submitting a public inquiry. A proposal or estimate is subject to its stated scope and validity period.</p>
        <p>Model usage, hosting, messaging, domains, licenses, and other external services may have separate charges. The client is responsible only for costs authorized under the Client Agreement. We identify any agreed pass-through charges and any markup rather than treating all external costs as automatically included.</p>
        <p>Deposits, refunds, cancellation charges, automatic renewal, and recurring-service cancellation follow the Client Agreement and mandatory law. These Terms alone do not authorize automatic billing or establish a nonrefundable deposit. Fee changes require the notice and agreement specified for the engagement.</p>
        <p>A client should notify us promptly of an invoice dispute, with enough detail to investigate it, and pay undisputed amounts when due. Any suspension for nonpayment must follow the Client Agreement and applicable notice requirements.</p>
      </>,
    },
    {
      id: "ownership",
      title: "Client data, software, and intellectual property",
      content: <>
        <p>The client retains its rights to supplied data, documents, content, business knowledge, and trademarks. It grants Pontian the access and limited use needed to perform the agreed services. That permission does not authorize unrelated reuse, sale, or disclosure of client information.</p>
        <p>The Client Agreement must state ownership of custom deliverables, source-code access, account control, any transfer conditions, and the client’s ongoing use rights. A statement that we build “owned software” does not by itself transfer every dependency or pre-existing component.</p>
        <p>Pontian retains rights to its pre-existing tools, methods, and reusable components unless expressly assigned. Where a delivered solution includes those components, the Client Agreement must provide the license needed for the agreed use. Open-source and third-party components remain subject to their own licenses. We do not claim exclusive ownership of material we have no right to assign.</p>
        <p>Use of a client’s name, logo, confidential work, or nonpublic results in publicity requires its permission. General skills and experience may be reused without disclosing confidential information or copying client-owned material.</p>
      </>,
    },
    {
      id: "confidentiality",
      title: "Confidentiality and data protection",
      content: <>
        <p>For an incorporated engagement, each party protects the other’s nonpublic information identified as confidential or reasonably understood to be confidential. It uses that information for the engagement and shares it only with people who need it and are bound by suitable obligations.</p>
        <p>This duty does not cover information lawfully public without a breach, already lawfully known, independently developed, or lawfully received without a confidentiality restriction. A legally required disclosure must be limited to what is required, with advance notice where legally permitted.</p>
        <p>The client is responsible for its lawful authority to supply information and grant access. Pontian is responsible for processing it within the agreed instructions and applicable obligations. The parties must establish any required processing, security, breach-notification, and international-transfer terms before personal or regulated data is handled.</p>
        <p>Neither party may assume that a generic policy makes a system suitable for patient data, student records, employment decisions, or another regulated use. Those uses require the applicable agreement, permissions, and validated controls. Confidentiality duties continue after termination for as long as the information remains confidential, including protection of trade secrets as required by law.</p>
      </>,
    },
    {
      id: "ai",
      title: "AI and human review",
      content: <>
        <p>AI may produce inaccurate, incomplete, outdated, biased, or unsupported output. Citations and access controls reduce particular risks but do not guarantee correctness. Check material facts against authoritative sources before relying on output.</p>
        <p>Authorized professionals and decision-makers remain responsible for engineering, safety, medical, legal, financial, employment, and other consequential decisions. AI drafts do not replace an approval, inspection, professional judgment, or a legally required procedure.</p>
        <p>A client engagement must identify approved model providers, permitted data, evaluation requirements, and which actions require human approval. Access to a model does not authorize it to publish documents, message customers, change a source system, or make a binding commitment. Those actions require the authority agreed for the workflow.</p>
        <p>Client data must not be used to train a general-purpose model or for another client’s benefit without the appropriate lawful basis and written client authorization. AI output ownership and permissible use depend on the Client Agreement, provider terms, third-party rights, and applicable law. We do not guarantee that an output is unique or eligible for intellectual-property protection.</p>
      </>,
    },
    {
      id: "integrations",
      title: "Integrations and third-party services",
      content: <>
        <p>An integration depends on authorized access, source-system capabilities, vendor terms, quotas, and ongoing availability. Providers may change an API, pricing, features, or access rules. We communicate a material effect on agreed work and address it under the Client Agreement.</p>
        <p>A working demo does not grant access to a provider or guarantee that a connector can be deployed in your environment. The client must maintain the accounts, licenses, and permissions allocated to it. Credentials must be exchanged through an agreed secure method.</p>
        <p>Third-party services, public links, telecom carriers, and property operators have their own terms and practices. We remain responsible for our own contractual duties, but do not control an independent provider’s decisions. We do not guarantee search placement, AI-search inclusion, platform approval, or a specific volume of leads.</p>
      </>,
    },
    {
      id: "termination",
      title: "Suspension, termination, and handoff",
      content: <>
        <p>We may restrict public website access to address abuse, a security risk, or a legal requirement. For a paid engagement, termination rights, notice periods, cure periods, and suspension procedures follow the Client Agreement. Urgent protective action must be limited to what is reasonably needed.</p>
        <p>At the end of an engagement, the parties settle amounts lawfully due and complete the agreed export, return or deletion of data, account transfer, and documentation handoff. Third-party retention, legal holds, and license limits may affect that process and must be disclosed.</p>
        <p>Continued hosting, maintenance, transition assistance, source-code escrow, continuity packages, and an instance license are included only if the Client Agreement provides for them. Expiration does not erase rights already earned or duties intended to continue, including confidentiality and restrictions on misuse of data.</p>
      </>,
    },
    {
      id: "disclaimers",
      title: "Website disclaimers and service warranties",
      content: <>
        <p>To the extent permitted by law, the public website and informational materials are provided “as is” and “as available,” without implied warranties of merchantability, fitness for a particular purpose, or noninfringement. We do not warrant uninterrupted access or that public information is complete or current.</p>
        <p>We may correct or remove website material and change public features. That does not permit us to withdraw a paid deliverable or an express warranty in a Client Agreement. For an incorporated engagement, the reasonable-care duty in these Terms and any express agreed warranties remain in effect.</p>
        <p>Nothing excludes a mandatory warranty, consumer remedy, or legal duty that cannot be excluded. Website information is not professional advice tailored to your circumstances.</p>
      </>,
    },
    {
      id: "liability",
      title: "Limits of liability",
      content: <>
        <p>To the extent permitted by law, neither party is liable under these Terms for indirect or consequential loss, lost profits, lost business opportunities, or lost goodwill. Loss recoverable under mandatory law remains recoverable.</p>
        <p>For claims arising only from the free public website or informational materials, Pontian’s total liability under these Terms is limited to US $100. Liability for paid services is governed by the Client Agreement. If that agreement incorporates these Terms and supplies no liability cap, each party’s total liability arising from the engagement is limited to the fees paid or payable to Pontian for the affected services during the twelve months before the event giving rise to the claim.</p>
        <p>These limits do not apply to fraud, willful misconduct, gross negligence, a client’s payment obligations, death or personal injury caused by negligence where exclusion is prohibited, or any liability that applicable law does not allow the parties to limit. A more specific allocation in the Client Agreement controls the engagement.</p>
      </>,
    },
    {
      id: "third-party-claims",
      title: "Third-party claims in business engagements",
      content: <>
        <p>For a business engagement that incorporates these Terms, the client is responsible for third-party claims caused by material it unlawfully supplies or its unlawful use of the delivered service. To the extent permitted by law, it must reimburse Pontian for reasonable defense costs and damages finally awarded or approved in a settlement for those claims.</p>
        <p>This responsibility does not extend to a claim caused by Pontian’s own breach, negligence, misconduct, or unauthorized modification. Pontian must promptly notify the client, allow it to manage a reasonable defense, and cooperate at the client’s expense. A settlement that admits wrongdoing by Pontian, imposes a nonmonetary duty on it, or leaves it liable requires its written consent. This provision does not impose an indemnity on an ordinary website visitor.</p>
      </>,
    },
    {
      id: "law",
      title: "Governing law and disputes",
      content: <>
        <p>For the public website, these Terms are governed by Florida law, excluding conflict-of-laws rules. Subject to mandatory jurisdiction rules, disputes may be brought in the state or federal courts with jurisdiction in Orange County, Florida. A Client Agreement may specify a different law and forum for its engagement.</p>
        <p>Contact us with a dispute so the parties can try to resolve it. That request does not prevent a timely court filing, emergency relief, a regulator complaint, or exercise of a statutory right. These Terms do not require arbitration or waive class-action rights.</p>
        <p>If consumer or other mandatory law entitles you to protections or a forum where you live, those rights prevail over an inconsistent provision here.</p>
      </>,
    },
    {
      id: "general",
      title: "Changes and general provisions",
      content: <>
        <p>We may revise these website Terms prospectively and update the revision date. Material changes receive additional notice where required. Changes to an existing Client Agreement require its amendment process and do not occur merely because we edit this page.</p>
        <p>If a provision is unenforceable, it is limited or removed to the extent necessary and the remaining provisions continue. Failure to enforce a provision once is not a permanent waiver. An engagement’s transfer, subcontracting, or assignment follows its Client Agreement and applicable law.</p>
        <p>These Terms and documents expressly incorporated into a Client Agreement govern their stated subjects. They do not convert an illustrative presentation into a contract, authorize new data processing, or override mandatory law. Electronic signatures and accepted electronic records may be used where legally valid.</p>
      </>,
    },
    {
      id: "contact",
      title: "Contact and legal notices",
      content: <LegalContact />,
    },
  ],
};
